### ISSUE TITLE
Use shortcode to embed video 

### ISSUE THREAD

**Issue by epogrebnyak** [cmf-team/cmf-team.github.io#4]
Todo:

- There is [a sample video at the end of index.md](https://github.com/epogrebnyak/cmf-team/blob/main/index.md#sample-video)
- I would like to have video embedded at the page using a shortcode
- The Premier theme should remain remote

What I tried:
- adding https://github.com/dommmel/jekyll-youtube did not help (maybe because we use remote theme)
- https://github.com/jeffreytse/jekyll-spaceship seems popular 
- confused about how to add plugins to jekyll, especially for remote theme

**Comment by epogrebnyak** [comment]
https://github.com/epogrebnyak/cmf-team/runs/7715914726?check_suite_focus=true

**Comment by epogrebnyak** [comment]
@super16 - в билде через Actions Gemfile не срабатывает (

**Comment by super16** [comment]
Заменил этап сборки в пайплайне, теперь всё собирается и деплоитсяс

**Comment by epogrebnyak** [comment]
@super16 , все билдится, видео показывает, большое спасибо
